---
name: Test
on:
  pull_request:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
      - uses: lowlydba/sustainable-npm@v1.1.0
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
