---
name: Test
on:
  pull_request:
  workflow_call:

permissions: {}

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out the repository
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20
      - uses: lowlydba/sustainable-npm@31d51025884f424f58f22e4e6578178bb4e79632 # v3.0.0
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build

  are-we-good:
    name: Are we good?
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    permissions: {}
    steps:
      - uses: lowlydba/are-we-good@4b62765391e357e78d0572113ab8b1c7d6b8d12a # v1.0.4
        with:
          jobs: ${{ toJSON(needs) }}
